services:
  notus-dev:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev
    
  notus-prod:
    build: .
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - .env  
    command: npm start